### PR TITLE
Fix #11

### LINKED ISSUE #11: `Plan::new` panics with invalid parameters.
When trying to construct 

```rust
concrete_ntt::prime64::Plan::try_new(2048, 1024)
```

the programs crashes (instead of returning `None`, as I would have expected):

```
thread 'main' panicked at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:56:13:
assertion failed: t_pow == 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/panicking.rs:127:5
   3: concrete_ntt::roots::sqrt_mod_ex64
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:56:13
   4: concrete_ntt::roots::find_primitive_root64
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:83:22
   5: concrete_ntt::prime64::Plan::try_new
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/prime64.rs:710:16
   6: bug_concrete_ntt::main
             at ./src/main.rs:4:22
   7: core::ops::function::FnOnce::call_once
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by tlepoint**

### CODE REVIEW

**Comment by IceTDrinker** [comment]
hello @tlepoint sorry your issue fell through the cracks, wil get back to you 🙂 for contributions we need a CLA to be signed and this repo does not seem to be properly configured for now

**Comment by IceTDrinker** [comment]
@cla-bot check

**Comment by IceTDrinker** [comment]
@sarah-ek while the CLA is being processed if you can take a look 🙂

**Comment by tlepoint** [comment]
I cannot easily sign such a CLA. Since I do not plan for now to contribute more extensively to Zama's source code, I'll close this PR, but now that it is on your radar, I would love if you could remove this panic one way or another! 

Thank you :)

**Comment by IceTDrinker** [comment]
noted, we'll take a look at the issue and propose a fix of our own then @tlepoint !

**Pull request closed without merging**
